version: "3"

services:
    api:
        build:
            context: ./api
            dockerfile: ../compose/api/Dockerfile
        volumes:
            - ./api:/app
            - /app/node_modules
        env_file:
            - ./api/local.env
        ports:
            - "3000:3000"
        networks:
            - testnetwork
        depends_on:
            - db
        command: ['npm', 'start']
    # webapp:

    db:
        image: mongo:4.2-bionic
        volumes:
            - mongo_data:/data/db
        env_file:
            - ./api/local.env
        networks:
            - testnetwork

volumes:
    mongo_data: {}

networks:
    testnetwork: {}
